# -*- coding: utf-8 -*-
"""Day_15_Embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UnI_WKDuK_6mL30JJHV4C7WVzb_OXbbm
"""

#  Scenario: University Library Search
# Imagine you’re building a smart search system for a university library.
# - Problem: Students often type queries like “fast dog running” or “canine sprinting”, but
# the library catalog has books titled “The dog runs fast”. Traditional keyword search misses these connections.
# - Solution: Use embeddings to capture semantic meaning instead of exact words.


from sentence_transformers import SentenceTransformer

# Choose from popular models:
# "all-MiniLM-L6-v2" → 384 dims, lightweight, fast
# "all-mpnet-base-v2" → 768 dims, stronger semantic understanding
# "BAAI/bge-m3" → 1024 dims, multilingual + dense/sparse retrieval
# "sentence-transformers/e5-large-v2" → 1024 dims, top performer on MTEB

model_name = "all-MiniLM-L6-v2"   # swap this to test other models
model = SentenceTransformer(model_name)

texts = [
    "The dog runs fast",
    "A quick canine sprints",
    "Python is a programming language"
]

embeddings = model.encode(texts)

print(f"Model: {model_name}")
print(f"Embedding shape: {embeddings.shape}")   # e.g. (3, 384) for MiniLM
print(f"First vector sample: {embeddings[0][:10]}")  # show first 10 values

# Scenario: Customer Support Chatbot Training
# Imagine you’re building a customer support chatbot for an e-commerce company.
# The chatbot needs to understand different types of sentences so it can respond appropriately.
# You feed it these sentences:
# - “Machine learning is a subset of AI”
# - “Deep learning uses neural networks”
# - “Bananas are yellow fruits”
# - “Artificial intelligence powers chatbots”

from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

sentences = [
    "Machine learning is a subset of AI",
    "Deep learning uses neural networks",
    "Bananas are yellow fruits",
    "Artificial intelligence powers chatbots"
]

embeddings = model.encode(sentences)

print(embeddings.shape)

# Simple cosine similarity example
import numpy as np

def cosine_similarity(a, b):
    return np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b))

a = np.array([0.2,0.8,-0.3,0.5])
b = np.array([0.1,0.9,-0.2,0.4])

print(cosine_similarity(a,b))

# Simple Euclidean Distance (L2 Distance) example
import numpy as np

a = np.array([1,2])
b = np.array([4,6])

distance = np.linalg.norm(a-b)

print(distance)

#example of Dot Product (Fastest Similarity Method)
import numpy as np

a = np.array([1,3,5])
b = np.array([2,4,6])

print(np.dot(a,b))

# Compute dot product similarity
a_norm = a / np.linalg.norm(a)
b_norm = b / np.linalg.norm(b)

np.dot(a_norm,b_norm)

# 🛒 Scenario: E‑Commerce Product Recommendations
# Imagine you’re building a smart recommendation engine for an online store.
# - Problem: Customers often search with phrases like “comfortable running shoes”, but the catalog has items
#  titled “lightweight sneakers for jogging”. Traditional keyword search struggles to connect these.
# - Solution: Use embeddings to capture semantic meaning of product descriptions and customer queries.

# Install required libraries
# pip install sentence-transformers scikit-learn

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# Step 1: Load embedding model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Step 2: Product catalog
products = [
    "Lightweight sneakers for jogging",
    "Wireless noise-cancelling headphones",
    "Comfortable cotton t-shirt for summer",
    "Smartwatch with heart rate monitor",
    "Laptop backpack with USB charging port"
]

# Step 3: Generate embeddings for products
product_embeddings = model.encode(products)

# Step 4: Recommendation function
def recommend_product(query):

    # Convert customer query into embedding
    query_embedding = model.encode([query])

    # Compute similarity
    similarity = cosine_similarity(query_embedding, product_embeddings)

    # Find most similar product
    best_match = similarity.argmax()

    return products[best_match]

# Step 5: Customer search
user_query = input("Search for a product: ")

recommended_product = recommend_product(user_query)

print("\nRecommended Product:", recommended_product)

# Scenario: Hospital FAQ Assistant
# A hospital wants to build a chatbot that helps patients quickly find answers to common questions.
# - Problem: Patients ask questions in different ways. For example:
# - “How do I book an appointment?”
# - “What’s the process to schedule a doctor visit?”
# - “Can I see a physician tomorrow?”
# Traditional keyword search might miss these connections.
# - Solution: Convert FAQs and patient queries into embeddings, then measure similarity to find the closest match.

# 👩‍💻 Code in Context
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# -----------------------------
# Step 1: Pretend these are FAQ embeddings
# (In reality, you'd generate them with a model like MiniLM or mpnet)
# Each vector is a simplified 4-dimensional embedding
faq1 = np.array([0.2, 0.8, -0.3, 0.5])   # "How do I book an appointment?"
faq2 = np.array([0.1, 0.9, -0.2, 0.4])   # "Process to schedule a doctor visit"
faq3 = np.array([-0.7, 0.1, 0.9, -0.5])  # "Visiting hours for patients"

# -----------------------------
# Step 2: Student query embedding
# Again, simplified for demonstration
query = np.array([0.19, 0.82, -0.25, 0.48])  # "Can I see a physician tomorrow?"

# -----------------------------
# Step 3: Cosine similarity
# Measures the angle between vectors (direction matters, not magnitude)
def cosine_sim(x, y):
    return np.dot(x, y) / (np.linalg.norm(x) * np.linalg.norm(y))

cos_sim1 = cosine_sim(query, faq1)
cos_sim2 = cosine_sim(query, faq2)
cos_sim3 = cosine_sim(query, faq3)

print("Cosine similarities (higher = more similar):")
print("FAQ1:", cos_sim1)
print("FAQ2:", cos_sim2)
print("FAQ3:", cos_sim3)

# -----------------------------
# Step 4: Euclidean distance
# Measures actual geometric distance (lower = more similar)
dist1 = np.linalg.norm(query - faq1)
dist2 = np.linalg.norm(query - faq2)
dist3 = np.linalg.norm(query - faq3)

print("\nEuclidean distances (lower = more similar):")
print("FAQ1:", dist1)
print("FAQ2:", dist2)
print("FAQ3:", dist3)

# -----------------------------
# Step 5: Dot product (normalized)
# Fastest metric, equivalent to cosine if vectors are normalized
query_norm = query / np.linalg.norm(query)
faq1_norm = faq1 / np.linalg.norm(faq1)
faq2_norm = faq2 / np.linalg.norm(faq2)
faq3_norm = faq3 / np.linalg.norm(faq3)

dot1 = np.dot(query_norm, faq1_norm)
dot2 = np.dot(query_norm, faq2_norm)
dot3 = np.dot(query_norm, faq3_norm)

print("\nDot products (normalized, same as cosine):")
print("FAQ1:", dot1)
print("FAQ2:", dot2)
print("FAQ3:", dot3)

# 📊 What Happens
# - Cosine similarity will show that the query is closest to FAQ1 and FAQ2 (both about appointments).
# - Euclidean distance will also confirm closeness, but it’s more sensitive to vector magnitude.
# - Dot product (if normalized) would give the same ranking as cosine, but faster.

# 🎯 Teaching Point
# This scenario shows how similarity metrics decide which FAQ answer to return:
# - Cosine similarity → best for text queries (robust to phrasing differences).
# - Euclidean distance → useful if absolute position matters (e.g., clustering patient queries).
# - Dot product → fastest option when vectors are normalized, ideal for large‑scale systems.

# 👉 In short: the code isn’t just math — it’s the engine behind semantic search and retrieval systems that make chatbots, recommendation engines, and assistants truly useful.
# Would you like me to design a business scenario (like customer support or HR policy search) next, so you can use it directly in your corporate training sessions?