# -*- coding: utf-8 -*-
"""Scenario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_1WijJe8qJohZdT_R75noxYlmsM6PCE7
"""

# # Scenario: Hospital Patient Record Search
# # - Problem: Doctors and nurses often type queries like “heart attack” or “chest pain emergency”, but the hospital’s electronic health record (EHR)
# system stores diagnoses as “acute myocardial infarction”. Traditional keyword search fails because medical staff use everyday language while records
#  use clinical terminology.
# # - Solution: Use embeddings to capture semantic meaning. Embeddings understand that “heart attack” and
# “acute myocardial infarction” are related concepts. This allows the search system to return the right patient records even when the
#  query wording doesn’t match the stored terminology.


from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Load embedding model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Example hospital patient records
patient_records = [
    {"id":1, "diagnosis":"acute myocardial infarction"},
    {"id":2, "diagnosis":"chronic obstructive pulmonary disease"},
    {"id":3, "diagnosis":"type 2 diabetes mellitus"},
    {"id":4, "diagnosis":"hypertension"},
    {"id":5, "diagnosis":"cardiac arrest"}
]

# Convert diagnoses into embeddings
diagnosis_texts = [record["diagnosis"] for record in patient_records]
diagnosis_embeddings = model.encode(diagnosis_texts)

# Doctor query
query = "heart attack emergency"

# Convert query to embedding
query_embedding = model.encode([query])

# Compute similarity
similarities = cosine_similarity(query_embedding, diagnosis_embeddings)

# Find most similar record
best_match_index = np.argmax(similarities)
best_record = patient_records[best_match_index]

print("Query:", query)
print("Most relevant patient record:")
print(best_record)

# # Scenario: E‑Commerce Product Search
# # - Problem: Shoppers often type queries like “cheap running shoes” or “affordable sneakers for jogging”, but the catalog
# lists products as “Budget-friendly athletic footwear”. Traditional keyword search misses these connections because customers use everyday
# language while product listings use marketing terms.
# # - Solution: Use embeddings to capture semantic meaning. Embeddings understand that “cheap running shoes” and
#  “budget-friendly athletic footwear” are related concepts. This ensures customers find the right products even when their
#  wording doesn’t match the catalog descriptions.

# Install libraries if needed
# pip install sentence-transformers scikit-learn

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# Step 1: Load embedding model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Step 2: Product catalog
products = [
    "Budget-friendly athletic footwear",
    "Premium leather formal shoes",
    "Lightweight sneakers for jogging",
    "Comfortable cotton sports t-shirt",
    "Running shorts for athletes"
]

# Step 3: Convert product descriptions into embeddings
product_embeddings = model.encode(products)

# Step 4: Product search function
def search_product(query):

    # Convert query to embedding
    query_embedding = model.encode([query])

    # Calculate cosine similarity
    similarity_scores = cosine_similarity(query_embedding, product_embeddings)

    # Get index of best match
    best_index = similarity_scores.argmax()

    return products[best_index], similarity_scores[0][best_index]

# Step 5: Customer search
user_query = input("Enter product search: ")

product, score = search_product(user_query)

print("\nBest Matching Product:", product)
print("Similarity Score:", round(score, 3))